### ISSUE TITLE
Unable to plot the results with the latest update

### ISSUE THREAD

**Issue by arindamsaha1507** [djgroen/FabCovid19#3]
Hi Derek,

I think this part of the code needs some changes with the latest updates.

https://github.com/djgroen/FabCovid19/blob/54b90bdb6907b2fa789f462f9c0704952aa47b69/visualisation/ValidateAvg.py#L88

I am unable to plot the results after using

``` 
fabsim localhost facs_postprocess:blackpool_localhost_1
```

The error I get is 

```
Traceback (most recent call last):
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/bin/fabsim", line 46, in <module>
    sys.exit(fabsim_main.main())
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/fabsim_main.py", line 150, in main
    env.exec_func(*env.task_args, **env.task_kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/decorators.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/fabsim/base/decorators.py", line 127, in wrapper
    return func(*args, **kwargs)
  File "/home/arindam/Dropbox/Brunel/FACS/FabSim/FabSim3/plugins/FabCovid19/visualisation/ValidateAvg.py", line 88, in facs_postprocess
    ci_multiplier = rundir.rsplit("-", 2)[2]
IndexError: list index out of range

```

**Comment by djgroen** [comment]
@arindamsaha1507 I made a simple fix now. Could you test to see if it works?

**Comment by arindamsaha1507** [comment]
Yes. The code now runs. Thank you.
